### ISSUE TITLE
Unreliable dragging of screen controls when hovering over other controls text or over the end edges of the screen

### ISSUE THREAD

**Issue by samuelventura** [samuelventura/athasha#46]

**Comment by samuelventura** [comment]
- Passing the temprary frame over its original control stops receiving the move event.
- Moving the temprary frame beyond the right and bottom edge of the screen also stops receiving the move event
- Strangely the cleanup is being called without getting a mouseUp event!

**Comment by samuelventura** [comment]
To make dragging reliable:
- Ensure label text is not overflowing. Smaller font size prevent the problem.
- Keep the controls withing the screen area by restricting going beyond borders
- Controls that get beyond the borders by a gridXY change can reliably be dragged back in
- Not really needed in the end, but added non selectable style with
```css
svg text {
    -webkit-user-select: none;
   -moz-user-select: none;
   -ms-user-select: none;
   user-select: none;
}
```
